# -*- coding: utf-8 -*-
"""group10_final_code_eon_llm_powered_email_drafting

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M_HVHlvblUZTY6U6q2xt9S_ExLyZsJyj


Aslihan Berber, Matriculation: 03798114
Mohammed Yazan Aljleilati, Matriculation: 03728944

TUM WS 25/26
"""

!pip install -q -U \
  transformers \
  bitsandbytes \
  accelerate \
  sentence-transformers \
  bertopic \
  hdbscan \
  umap-learn \
  nltk \
  peft \
  trl

import os
os.environ["WANDB_DISABLED"] = "true"
os.environ["WANDB_MODE"] = "disabled"
os.environ["ACCELERATE_MIXED_PRECISION"] = "no"

import torch, pandas as pd, numpy as np
from sentence_transformers import SentenceTransformer
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
import hdbscan, umap
import matplotlib.pyplot as plt
import os
import pandas as pd
import glob

device = "cuda" if torch.cuda.is_available() else "cpu"
print("Using:", device)

"""**Loading and Reading Input Mails into JSON File**"""

from google.colab import drive
drive.mount('/content/drive/')

import glob
import pandas as pd
#Loading the Emails
def load_emails(path_pattern="/content/drive/My Drive/DAIA_EON/GoldenDataset/*.txt"):
    emails = []
    for f in glob.glob(path_pattern):
        with open(f, "r", encoding="utf8") as fh:
            text = fh.read()
        emails.append({
            "email_id": f.split("/")[-1].replace(".txt", ""),
            "raw_text": text
        })
    return emails

emails = load_emails()

# Converting to DataFrame
df = pd.DataFrame(emails)

print("Loaded", len(df), "emails")
df.head()

# Output path for JSON Lines format (.jsonl)
output_path = "/content/drive/My Drive/DAIA_EON/emails_dataset.jsonl"
# Saving as JSONL
df.to_json(
    output_path,
    orient="records",   # each row becomes a separate JSON object
    lines=True,
    force_ascii=False   # keeps the text readable
)
print("Saved JSONL to:", output_path)

"""**Topic Detection and Clustering**"""

import pandas as pd

# Loading the JSONL
path_jsonl = "/content/drive/My Drive/DAIA_EON/emails_dataset.jsonl"

df = pd.read_json(path_jsonl, lines=True)

df.head()

# Extracting the list of email texts
documents = df["raw_text"].tolist()

len(documents), documents[0][:300]

from sentence_transformers import SentenceTransformer

# Multilingual model that supports German
model_name = "paraphrase-multilingual-mpnet-base-v2"
embedding_model = SentenceTransformer(model_name)

from sklearn.feature_extraction.text import CountVectorizer
import nltk
from nltk.corpus import stopwords

# Downloading NLTK stopwords once
nltk.download("stopwords")

# 1) German stopwords from NLTK
german_stopwords = set(stopwords.words("german"))

# 2) Extra specific stopwords for German emails
extra_stopwords = {
    "damen", "herren", "sehr", "geehrte", "geehrten", "geehrter",
    "vielen", "dank", "gruß", "grüße", "gruesse",
    "mit", "freundlichen",
    "eon", "energie", "kundenservice", "kundendienst", "kundennummer",
    "guten", "tag", "hallo", "liebe", "lieben"
}

# 3) Combining
all_stopwords = german_stopwords.union(extra_stopwords)

# 4) Vectorizer for BERTopic
vectorizer_model = CountVectorizer(
    stop_words=list(all_stopwords),
    ngram_range=(1, 2),  # 1- and 2-word phrases
    min_df=2             # ignores words that appear only once
)

from bertopic import BERTopic

topic_model = BERTopic(
    embedding_model=embedding_model,
    language="german",
    vectorizer_model=vectorizer_model,
    min_topic_size=3,
    calculate_probabilities=True,
    verbose=True
)

topics, probs = topic_model.fit_transform(documents)


#topics → list with topic ID for each email (e.g. 0, 1, 2, ...)

#probs → probability distribution over topics for each email

import numpy as np

# using fitted vectorizer from BERTopic
cv = topic_model.vectorizer_model

# document-term matrix
X = cv.transform(documents)

# df = how many emails contain each term
doc_freq = np.asarray((X > 0).sum(axis=0)).ravel()

vocab = cv.get_feature_names_out()
df_dict = dict(zip(vocab, doc_freq))

list(df_dict.items())[:20]

# Overview of the topics
topic_info = topic_model.get_topic_info()
topic_info.head(10)

"""**Topic Labeling**"""

import pandas as pd
import re

# Words we don't want to see in labels
label_stopwords = {
    # German greeting / boilerplate
    "grüßen", "grußen", "gruss", "gruß", "hiermit", "sende", "bitte",
    "nachricht", "wurde", "neuen", "bereits", "gerne",
    # misc junk / technical
    "android", "mobiltelefon", "example", "gmbh", "co", "kg",
    "the", "or", "on", "com", "mfg", "aufgrund"
}

# Minimum document frequency for label words selected manually
MIN_DF_FOR_LABEL = 5

def clean_candidate(word: str) -> str | None:
    w = word.lower().strip()

    # filtering by document frequency (this removes names)
    if df_dict.get(w, 0) < MIN_DF_FOR_LABEL:
        return None

    # removing tokens with digits
    if any(ch.isdigit() for ch in w):
        return None

    # removing very short tokens
    if len(w) < 3:
        return None

    # filtering by valid characters (letters + optional underscore)
    if not re.match(r"^[a-zäöüß]+(_[a-zäöüß]+)?$", w):
        return None

    if w in label_stopwords:
        return None

    return w

def make_label(topic_id: int) -> str:
    if topic_id == -1:
        return "Sonstige / Ausreißer"

    words_scores = topic_model.get_topic(topic_id)
    clean_words = []
    for w, _ in words_scores:
        cw = clean_candidate(w)
        if cw is None:
            continue
        clean_words.append(cw.replace("_", " "))
        if len(clean_words) == 3:
            break

    if not clean_words:
        return f"Topic {topic_id}"

    return " / ".join(clean_words)

topic_labels = []
for t in topic_info["Topic"]:
    topic_labels.append({"topic_id": t, "topic_label": make_label(t)})

labels_df = pd.DataFrame(topic_labels)
labels_df

import pandas as pd

# Final chosen topic titles
final_topic_names = {
    -1: "Sonstiges",
     0: "Überweisung / Rückzahlung",
     1: "Stromversorgung",
     2: "Bestätigung",
     3: "Strommeldung",
     4: "Zählerstand / Zählerplatz",
     5: "Vertragspartner / Bestätigung",
     6: "Stromzähler-Anfrage",
     7: "Rechnungsanfrage",
     8: "Vertragsnummer ändern",
     9: "Online-Verträge / Portal",
    10: "Daten & Vertragskonto",
    11: "Portal-Zugang / E-Mail-Probleme",
    12: "Stromvertrag / Grundvertrag",
    13: "Vertrag allgemein",
    14: "Zählerunterlagen / Fehler",
}

# Building labels_df from topic_info + mapping
labels_df = topic_info[["Topic"]].rename(columns={"Topic": "topic_id"})
labels_df["topic_label"] = labels_df["topic_id"].map(final_topic_names)

labels_df

import numpy as np

# Adding cluster info to main dataframe
df["topic_id"] = topics
df["topic_confidence"] = probs.max(axis=1)

# id -> label mapping
id2label = dict(zip(labels_df["topic_id"], labels_df["topic_label"]))

df["topic_label"] = df["topic_id"].map(id2label)


df[["email_id", "topic_id", "topic_label", "topic_confidence"]].head()

# Counting the emails per topic
topic_counts = (
    df.groupby("topic_id")
      .size()
      .reset_index(name="count")
      .merge(labels_df, on="topic_id", how="left")
      .sort_values("count", ascending=False)
      .reset_index(drop=True)
)

topic_counts

plt.figure(figsize=(8, 8))
plt.pie(
    topic_counts["count"],
    labels=topic_counts["topic_label"],
    autopct="%1.1f%%",
    startangle=140
)
plt.title("Topic Distribution (Percent)")
plt.show()

"""Fine Tuning Section"""

import os, glob, re
import pandas as pd

pairs_folder = "/content/drive/My Drive/DAIA_EON/GoldenDatasetAnswers"

def parse_pair_file(path):
    with open(path, "r", encoding="utf-8") as f:
        text = f.read()

    # Normalizing: removing BOM, normalizing newlines
    text = text.replace("\ufeff", "")
    text = text.replace("\r\n", "\n").replace("\r", "\n")

    lines = text.split("\n")

    def find_index(prefixes):
        """Find first line that starts with any of the given prefixes (case-insensitive)."""
        for i, line in enumerate(lines):
            s = line.strip().lower()
            for p in prefixes:
                if s.startswith(p):
                    return i
        return None

    # Allowing several variations, just in case
    idx_input   = find_index(["input", "input:"])
    idx_formal  = find_index(["formal output", "formal output:", "formal ouput:"])
    idx_friendly = find_index([
        "friendly output", "friendly output:", "freindly output:", "friendly ouput:",
        "friendly ouput", "friendly ouput:",
        "freundlich output:"
    ])

    if idx_input is None or idx_formal is None or idx_friendly is None:
        raise ValueError(
            f"Could not find all sections (input/formal/friendly). "
            f"Found indices: input={idx_input}, formal={idx_formal}, friendly={idx_friendly}"
        )

    # Slicing the text blocks between the markers
    input_text = "\n".join(lines[idx_input+1:idx_formal]).strip()
    formal_text = "\n".join(lines[idx_formal+1:idx_friendly]).strip()
    friendly_text = "\n".join(lines[idx_friendly+1:]).strip()

    return {
        "file": os.path.basename(path),
        "input": input_text,
        "formal": formal_text,
        "friendly": friendly_text,
    }

# Re-running the parsing
records = []
for fp in sorted(glob.glob(os.path.join(pairs_folder, "*.txt"))):
    try:
        records.append(parse_pair_file(fp))
    except Exception as e:
        print("ERROR in", fp, "->", e)

df_pairs = pd.DataFrame(records)
print("Parsed files:", len(df_pairs))
df_pairs.head()

import transformers, torch
print("transformers:", transformers.__version__)
print("torch:", torch.__version__)

# Commented out IPython magic to ensure Python compatibility.
# %pip install -q -U bitsandbytes==0.49.0 transformers accelerate peft trl

from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
import torch

tiny_name = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
print("Trying to load:", tiny_name)

bnb = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_compute_dtype=torch.bfloat16,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
)

tokenizer = AutoTokenizer.from_pretrained(tiny_name)
print("TinyLlama tokenizer loaded")

model = AutoModelForCausalLM.from_pretrained(
    tiny_name,
    quantization_config=bnb,
    device_map="auto",
    torch_dtype=torch.bfloat16,
)
print("TinyLlama model loaded")

import json

# These are the instructions the model learns to follow
FORMAL_INSTR = (
    "Du bist ein KI-Assistent, der Mitarbeitende im E.ON-Kundenservice unterstützt. "
    "Formuliere eine formelle, klare und höfliche Antwort-E-Mail auf Deutsch."
)

FRIENDLY_INSTR = (
    "Du bist ein KI-Assistent, der Mitarbeitende im E.ON-Kundenservice unterstützt. "
    "Formuliere eine freundliche und weniger formelle Antwort-E-Mail auf Deutsch."
)

training_records = []

for _, row in df_pairs.iterrows():
    email = (row["input"] or "").strip()
    formal = (row["formal"] or "").strip()
    friendly = (row["friendly"] or "").strip()

    if not email or not formal or not friendly:
        continue

    # formal example
    training_records.append({
        "instruction": FORMAL_INSTR,
        "input": email,
        "output": formal,
    })

    # friendly example
    training_records.append({
        "instruction": FRIENDLY_INSTR,
        "input": email,
        "output": friendly,
    })

print("Total training examples:", len(training_records))
training_records[0]

train_jsonl = "/content/drive/My Drive/DAIA_EON/eon_tinyllama_training_data.jsonl"

with open(train_jsonl, "w", encoding="utf-8") as f:
    for rec in training_records:
        f.write(json.dumps(rec, ensure_ascii=False) + "\n")

print("Saved training data to:", train_jsonl)

from datasets import load_dataset

dataset = load_dataset("json", data_files={"train": train_jsonl})["train"]
print("Total raw examples:", len(dataset))
print(dataset[0])

# 80/20 train/validation split
splits = dataset.train_test_split(test_size=0.2, seed=42)
train_ds = splits["train"]
eval_ds  = splits["test"]

len(train_ds), len(eval_ds)

def format_example(example):
    system = example["instruction"]
    user   = example["input"]
    answer = example["output"]

    text = (
        f"{system}\n\n"
        f"Kunden-E-Mail:\n{user}\n\n"
        f"Antwort:\n{answer}"
    )
    return {"text": text}

train_ds = train_ds.map(format_example)
eval_ds  = eval_ds.map(format_example)

# keeping only "text" column
train_ds = train_ds.remove_columns([c for c in train_ds.column_names if c != "text"])
eval_ds  = eval_ds.remove_columns([c for c in eval_ds.column_names if c != "text"])

train_ds[0]

'''
import torch
torch.set_default_dtype(torch.float16)

from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
from peft import LoraConfig
from trl import SFTTrainer, SFTConfig
'''

'''
model_name = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
)

tokenizer = AutoTokenizer.from_pretrained(model_name)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    quantization_config=bnb_config,
    device_map="auto",
    torch_dtype=torch.float16,
)
'''

'''
lora_config = LoraConfig(
    r=8,
    lora_alpha=16,
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM",
    target_modules=["q_proj","k_proj","v_proj","o_proj","gate_proj","up_proj","down_proj"],
)
'''

'''
from trl import SFTConfig

sft_config = SFTConfig(
    output_dir="/content/drive/My Drive/DAIA_EON/tinyllama_eon_qlora",

    # batch handling
    per_device_train_batch_size=1,
    gradient_accumulation_steps=8,   # effective batch = 8

    # training length
    max_steps=600,
    warmup_ratio=0.05,

    # stability
    learning_rate=2e-5,
    max_grad_norm=0.3,

    # logging / saving
    logging_steps=25,
    save_steps=300,
    save_total_limit=2,

    # precision
    fp16=False,
    bf16=False,

    # QLoRA optimizer
    optim="paged_adamw_8bit",

    report_to=[],
)

'''

'''
from trl import SFTTrainer
trainer = SFTTrainer(
    model=model,              # loaded base model
    train_dataset=train_ds,
    eval_dataset=eval_ds,
    peft_config=lora_config,
    args=sft_config,
)

# safety: ensuring no scaler
if hasattr(trainer.accelerator, "scaler"):
    trainer.accelerator.scaler = None

trainer.train()
'''

'''
print("Eval samples:", len(eval_ds))
print("Global step:", trainer.state.global_step)
'''

'''
metrics = trainer.evaluate()
print(metrics)
'''

'''
train_ds[0]
eval_ds[0]
'''

'''
import torch
torch.set_default_dtype(torch.float16)
'''

'''
# Checking for empty / tiny examples
lengths = [len(tokenizer(x["text"]).input_ids) for x in eval_ds.select(range(min(50, len(eval_ds))))]
print("min/max token length:", min(lengths), max(lengths))
print("num very short (<20):", sum(l < 20 for l in lengths))
'''

#eval_ds[0]["text"][:500]

'''
print(len(train_ds))
print(len(eval_ds))
'''

'''
import torch

def check_nans_in_lora(m):
    nan_params = []
    inf_params = []
    for n, p in m.named_parameters():
        if "lora_" in n:
            if torch.isnan(p).any():
                nan_params.append(n)
            if torch.isinf(p).any():
                inf_params.append(n)
    print("LoRA params with NaNs:", len(nan_params))
    print("LoRA params with Infs:", len(inf_params))
    if nan_params: print("Example NaN:", nan_params[0])
    if inf_params: print("Example Inf:", inf_params[0])

check_nans_in_lora(trainer.model)
'''

"""**Testing Our Model (Generation Tests)**"""

'''
import os, re, torch
from transformers import AutoTokenizer, AutoModelForCausalLM
from peft import PeftModel

base_name = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
lora_root = "/content/drive/My Drive/DAIA_EON/tinyllama_eon_qlora"
out_dir   = "/content/drive/My Drive/DAIA_EON/tinyllama_eon_merged"

# Picking the latest checkpoint
if not os.path.exists(lora_root):
    raise FileNotFoundError(f"LoRA root not found: {lora_root}")

ckpts = [
    os.path.join(lora_root, d)
    for d in os.listdir(lora_root)
    if d.startswith("checkpoint-") and os.path.isdir(os.path.join(lora_root, d))
]
if not ckpts:
    raise RuntimeError(f"No checkpoints found in {lora_root}")

def step_num(p: str) -> int:
    m = re.search(r"checkpoint-(\d+)", os.path.basename(p))
    return int(m.group(1)) if m else -1

ckpt = max(ckpts, key=step_num)
print("Using checkpoint:", ckpt)

# Tokenizer
tokenizer = AutoTokenizer.from_pretrained(base_name, use_fast=False)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

# Load base model (fp16)
base = AutoModelForCausalLM.from_pretrained(
    base_name,
    torch_dtype=torch.float16,
    device_map="auto",
)

# Loading LoRA + merge
model_ft = PeftModel.from_pretrained(base, ckpt)
model_ft = model_ft.merge_and_unload()

# Setting config ids
model_ft.config.pad_token_id = tokenizer.pad_token_id
model_ft.config.eos_token_id = tokenizer.eos_token_id

model_ft.eval()

# Saving merged model
os.makedirs(out_dir, exist_ok=True)
model_ft.save_pretrained(out_dir, safe_serialization=True)
tokenizer.save_pretrained(out_dir)

print("Saved merged model to:", out_dir)
print("Device:", next(model_ft.parameters()).device)
'''

import re
import torch

# 1) Topic (BERTopic)
def get_topic_label(email_text: str) -> str:
    # topic_model + final_topic_names exist/come from our BERTopic section
    t_id, _ = topic_model.transform([email_text])
    t_id = int(t_id[0])
    return final_topic_names.get(t_id, "Sonstiges")

# 2) Short summary (rule-based)
def short_summary(email_text: str, max_sentences: int = 2) -> str:
    text = email_text.strip()

    drop_lines = []
    for line in text.splitlines():
        l = line.strip()
        if not l:
            continue
        if re.match(r"^(hallo|guten tag|sehr geehrte|liebe|freundliche grüße|mit freundlichen grüßen)", l.lower()):
            continue
        drop_lines.append(l)

    clean = " ".join(drop_lines)

    sents = re.split(r"(?<=[\.\!\?])\s+", clean)
    sents = [s.strip() for s in sents if s.strip()]
    return " ".join(sents[:max_sentences]) if sents else clean[:220]

# 3) Reply generation
@torch.no_grad()
def generate_reply(email_text: str, tone: str = "formal", max_new_tokens: int = 220):

    tone = tone.lower().strip()

    if tone == "formal":
        instr = (
            FORMAL_INSTR + "\n"
            "Stilregeln:\n"
            "- Sehr formell und sachlich\n"
            "- Höfliche Distanz (Sie-Form)\n"
            "- Keine lockeren Formulierungen\n"
            "- Klassische Grußformel\n"
        )
        tone_tag = "TON: FORMELL"
    else:
        instr = (
            FRIENDLY_INSTR + "\n"
            "Stilregeln:\n"
            "- Freundlich, empathisch, aber professionell\n"
            "- Einfachere Sprache\n"
            "- Kürzere Sätze\n"
            "- Etwas wärmerer Ton\n"
        )
        tone_tag = "TON: FREUNDLICH"

    safety = (
        "WICHTIG (Compliance-Regeln):\n"
        "1) Antworte ausschließlich auf Basis der Kunden-E-Mail.\n"
        "2) Erfinde KEINE neuen Fakten: keine Nummern, Beträge, Zählerstände, Daten/Zeiträume, Orte/Adressen, Telefon/E-Mail.\n"
        "3) Wenn du Zahlen oder Daten erwähnst, dann NUR wenn sie in der Kunden-E-Mail stehen – und dann GENAU unverändert (keine Rundung, keine Umformatierung, keine zusätzlichen Ziffern).\n"
        "4) Wenn du dir bei einer Zahl/einem Datum nicht sicher bist: NICHT verwenden, sondern nachfragen.\n"
        "5) Behaupte niemals, dass bereits gezahlt/überwiesen wurde, außer der Kunde schreibt das explizit.\n"
        "6) Keine frei erfundenen Zeitangaben (z.B. 'am 22.02.2022', 'seit 2019') – nur wenn exakt so im Text.\n"
        "7) Wenn Infos fehlen, stelle 2–4 konkrete Rückfragen.\n"
    )

    prompt = (
        f"{instr}\n"
        f"{tone_tag}\n\n"
        f"{safety}\n"
        f"Kunden-E-Mail:\n{email_text}\n\n"
        f"Antwort:\n"
    )


    global model_ft, tokenizer

    if "model_ft" not in globals() or "tokenizer" not in globals():
        from transformers import AutoTokenizer, AutoModelForCausalLM

        MERGED_DIR = "/content/drive/My Drive/DAIA_EON/tinyllama_eon_merged"
        tokenizer = AutoTokenizer.from_pretrained(MERGED_DIR, use_fast=False)
        if tokenizer.pad_token is None:
            tokenizer.pad_token = tokenizer.eos_token

        model_ft = AutoModelForCausalLM.from_pretrained(
            MERGED_DIR,
            torch_dtype=torch.float16,
            device_map="auto",
        )
        model_ft.eval()
        model_ft.config.pad_token_id = tokenizer.pad_token_id
        model_ft.config.eos_token_id = tokenizer.eos_token_id

    model = model_ft
    model.eval()

    if tokenizer.pad_token_id is None:
        tokenizer.pad_token = tokenizer.eos_token
    model.config.pad_token_id = tokenizer.pad_token_id

    device = next(model.parameters()).device
    inputs = tokenizer(prompt, return_tensors="pt", truncation=True, max_length=1024)
    inputs = {k: v.to(device) for k, v in inputs.items()}

    out = model.generate(
        **inputs,
        do_sample=False,
        num_beams=3,
        repetition_penalty=1.15,
        no_repeat_ngram_size=4,
        max_new_tokens=max_new_tokens,
        eos_token_id=tokenizer.eos_token_id,
        pad_token_id=tokenizer.pad_token_id,
    )

    text = tokenizer.decode(out[0], skip_special_tokens=True)
    reply = text.split("Antwort:", 1)[1].strip() if "Antwort:" in text else text.strip()

    # cleaning duplicate signatures if model repeats them
    reply = re.sub(
        r"(\nMit freundlichen Grüßen.*?E\.ON Kundenservice)\s*\1",
        r"\1",
        reply,
        flags=re.DOTALL
    )

    # enforcing E.ON signature once
    if "E.ON Kundenservice" not in reply:
        reply = reply.rstrip() + "\n\nMit freundlichen Grüßen\n[Ihr Name]\nE.ON Kundenservice"

    return reply

# 4) Combined output
def generate_with_topic_summary(email_text: str):
    topic = get_topic_label(email_text)
    summ  = short_summary(email_text)

    formal = generate_reply(email_text, "formal")
    friendly = generate_reply(email_text, "friendly")

    print("THEMA:", topic)
    print("KURZBESCHREIBUNG:", summ)
    print("\n" + "="*80)
    print("FORMAL:\n", formal)
    print("\n" + "="*80)
    print("FRIENDLY:\n", friendly)

#trial email (a new email that was not used in training)
generate_with_topic_summary(email_text = """Hallo.
Ich entschuldige mich für die entstandenen Schulden und möchte hiermit eine Abwendungsvereinbarung mit ihnen treffen.
Leider konnte ich die Summe nicht direkt zahlen. Die erste Rate in Höhe von 49,57€ werde ich so schnell wie möglich überweisen.
Kundenummer:3657872389
Freundliche Grüße Stella Benner""")

import random
import pandas as pd

# Extracting just the customer email from the stored training-style text
def extract_customer_email(full_text: str) -> str:
    start_key = "Kunden-E-Mail:\n"
    end_key = "\n\nAntwort:"
    if start_key in full_text and end_key in full_text:
        return full_text.split(start_key, 1)[1].split(end_key, 1)[0].strip()
    return full_text.strip()


def generate_pack(email_text: str):

    topic = get_topic_label(email_text)
    summ  = short_summary(email_text)

    formal = generate_reply(email_text, "formal")
    friendly = generate_reply(email_text, "friendly")

    return topic, summ, formal, friendly

# sample 10 eval examples (never used in training)
N = 10
random.seed(42)

# Safety in case eval_ds is empty
if len(eval_ds) == 0:
    raise ValueError("eval_ds is empty. Check your dataset split / loading.")

idxs = random.sample(range(len(eval_ds)), k=min(N, len(eval_ds)))
print("Eval indices sampled:", idxs)

rows = []
for i, idx in enumerate(idxs, 1):
    full_text = eval_ds[idx]["text"]
    email = extract_customer_email(full_text)

    topic, summ, formal, friendly = generate_pack(email)

    rows.append({
        "eval_index": idx,
        "topic": topic,
        "summary": summ,
        "customer_email": email,
        "formal_output": formal,
        "friendly_output": friendly,
    })

    print("\n" + "="*90)
    print(f"[{i}/{len(idxs)}] eval_index={idx}")
    print("THEMA:", topic)
    print("KURZBESCHREIBUNG:", summ)
    print("- CUSTOMER EMAIL:\n", email[:1200])  # first ~1200 chars
    print("\n- FORMAL OUTPUT:\n", formal[:1200])
    print("\n- FRIENDLY OUTPUT:\n", friendly[:1200])

# putting into a DataFrame for easy review
df_gen = pd.DataFrame(rows)
df_gen

out_path = "/content/drive/My Drive/DAIA_EON/generation_eval_10_results.csv"
df_gen.to_csv(out_path, index=False)
print("Saved CSV to:", out_path)

"""**Validation Checks**"""

import numpy as np
import re
from collections import Counter
from sklearn.metrics.pairwise import cosine_similarity
from sentence_transformers import SentenceTransformer
import matplotlib.pyplot as plt

# Sentence embedding model (small + fast)
embedder = SentenceTransformer("all-MiniLM-L6-v2")

def normalize_text(t):
    t = t.lower()
    t = re.sub(r"\s+", " ", t)
    return t.strip()

# Combining formal + friendly
all_outputs = (
    df_gen["formal_output"].tolist()
    + df_gen["friendly_output"].tolist()
)

texts = [normalize_text(t) for t in all_outputs]

# 1) Lexical entropy
def lexical_entropy(text):
    tokens = text.split()
    if not tokens:
        return 0.0
    freqs = np.array(list(Counter(tokens).values()), dtype=float)
    probs = freqs / freqs.sum()
    return -np.sum(probs * np.log(probs + 1e-9))

lex_entropies = [lexical_entropy(t) for t in texts]

# 2) Semantic similarity matrix
embs = embedder.encode(texts, normalize_embeddings=True)
sim_matrix = cosine_similarity(embs)

# removing diagonal
upper_sims = sim_matrix[np.triu_indices(len(sim_matrix), k=1)]

print("Lexical entropy:")
print("  mean:", np.mean(lex_entropies))
print("  std :", np.std(lex_entropies))

print("\nSemantic similarity:")
print("  mean:", np.mean(upper_sims))
print("  std :", np.std(upper_sims))


plt.figure()
plt.hist(lex_entropies, bins=15)
plt.title("Lexical Entropy Distribution")
plt.xlabel("Entropy")
plt.ylabel("Count")
plt.show()

plt.figure()
plt.hist(upper_sims, bins=15)
plt.title("Pairwise Semantic Similarity")
plt.xlabel("Cosine similarity")
plt.ylabel("Count")
plt.show()

import re
import pandas as pd

# Extracting candidate "facts"
NUM_PATTERN = re.compile(r"(?<!\w)(?:\d[\d\s\-/\.]{1,}\d|\d)(?!\w)")  # includes 49,57 / 103,22 / 232 671 429 363 etc.
DATE_PATTERN = re.compile(r"\b(?:\d{1,2}[.\-/]\d{1,2}[.\-/]\d{2,4}|\d{4}[.\-/]\d{1,2}[.\-/]\d{1,2})\b")
EMAIL_PATTERN = re.compile(r"\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b")
URL_PATTERN = re.compile(r"\b(?:https?://|www\.)\S+\b", re.IGNORECASE)
PHONE_PATTERN = re.compile(r"\b(?:\+?\d{1,3}[\s\-]?)?(?:\(?\d{2,5}\)?[\s\-]?)?\d{3,}[\s\-]?\d{2,}\b")

def normalize_token(s: str) -> str:
    # normalizing spacing to compare "232 671" vs "232671"
    s = re.sub(r"\s+", "", s)
    return s.strip()

def extract_facts(text: str):
    text = str(text)

    nums = {normalize_token(x) for x in NUM_PATTERN.findall(text)}
    dates = {normalize_token(x) for x in DATE_PATTERN.findall(text)}
    emails = {x.lower() for x in EMAIL_PATTERN.findall(text)}
    urls = {x.lower() for x in URL_PATTERN.findall(text)}
    phones = {normalize_token(x) for x in PHONE_PATTERN.findall(text)}

    # removing tiny/meaningless numeric fragments
    nums = {x for x in nums if len(x) >= 3}  # keep 10322, 407982866, 49,57 becomes 49,57 -> normalized "49,57" -> "49,57" -> then remove spaces only, still length>=3

    return {
        "nums": nums,
        "dates": dates,
        "emails": emails,
        "urls": urls,
        "phones": phones,
    }

def hallucination_flags(customer_email: str, reply: str):
    e = extract_facts(customer_email)
    r = extract_facts(reply)

    extra_nums = sorted(list(r["nums"] - e["nums"]))
    extra_dates = sorted(list(r["dates"] - e["dates"]))
    extra_emails = sorted(list(r["emails"] - e["emails"]))
    extra_urls = sorted(list(r["urls"] - e["urls"]))
    extra_phones = sorted(list(r["phones"] - e["phones"]))

    # risk if reply introduces any new "fact-like" strings
    risk = any([
        len(extra_nums) > 0,
        len(extra_dates) > 0,
        len(extra_emails) > 0,
        len(extra_urls) > 0,
        len(extra_phones) > 0,
    ])

    return {
        "hallucination_risk": bool(risk),
        "extra_nums": extra_nums[:20],
        "extra_dates": extra_dates[:20],
        "extra_emails": extra_emails[:20],
        "extra_urls": extra_urls[:20],
        "extra_phones": extra_phones[:20],
    }

# applying to df_gen
df_gen["formal_hallucination"] = df_gen.apply(
    lambda r: hallucination_flags(r["customer_email"], r["formal_output"]), axis=1
)
df_gen["friendly_hallucination"] = df_gen.apply(
    lambda r: hallucination_flags(r["customer_email"], r["friendly_output"]), axis=1
)

df_gen["formal_risk"] = df_gen["formal_hallucination"].apply(lambda x: x["hallucination_risk"])
df_gen["friendly_risk"] = df_gen["friendly_hallucination"].apply(lambda x: x["hallucination_risk"])

print("Formal hallucination rate:", float(df_gen["formal_risk"].mean()))
print("Friendly hallucination rate:", float(df_gen["friendly_risk"].mean()))

# showing the worst cases (flagged)
display_cols = ["eval_index", "topic", "summary", "customer_email", "formal_output", "friendly_output",
                "formal_hallucination", "friendly_hallucination", "formal_risk", "friendly_risk"]

flagged = df_gen[df_gen["formal_risk"] | df_gen["friendly_risk"]][display_cols]
print("\nFlagged rows:", len(flagged), "out of", len(df_gen))

# Showing a compact view first
compact_cols = ["eval_index", "formal_risk", "friendly_risk", "formal_hallucination", "friendly_hallucination"]
display(flagged[compact_cols].head(10))

"""**Streamlit WebApp**"""

!pip -q install streamlit

topic_save_dir = "/content/drive/My Drive/DAIA_EON/bertopic_model"
topic_model.save(topic_save_dir)

names_path = "/content/drive/My Drive/DAIA_EON/final_topic_names.txt"
with open(names_path, "w", encoding="utf-8") as f:
    for k, v in final_topic_names.items():
        f.write(f"{k}\t{v}\n")

print("Saved topic model to:", topic_save_dir)
print("Saved topic names to:", names_path)

# Trying to empty cache
import torch
torch.cuda.empty_cache()

# Commented out IPython magic to ensure Python compatibility.
# 
# %%writefile app.py
# import os
# import re
# import html
# import streamlit as st
# import streamlit.components.v1 as components
# import torch
# from transformers import AutoTokenizer, AutoModelForCausalLM
# 
# 
# # CONFIGURATIONS
# 
# MERGED_MODEL_DIR = "/content/drive/My Drive/DAIA_EON/tinyllama_eon_merged"
# 
# TOPIC_MODEL_DIR = "/content/drive/My Drive/DAIA_EON/bertopic_model"
# TOPIC_NAMES_PATH = "/content/drive/My Drive/DAIA_EON/final_topic_names.txt"
# 
# MAX_NEW_TOKENS = 220
# TOPIC_MIN_PROB = 0.35
# 
# 
# # UI helper: Copy button
# 
# def copy_button(text: str, label: str = "Copy"):
#     safe = html.escape(text).replace("\n", "\\n").replace("\r", "")
#     components.html(
#         f"""
#         <button style="
#             padding: 0.55rem 0.95rem;
#             border-radius: 0.7rem;
#             border: 1px solid rgba(255,255,255,0.22);
#             background: rgba(255,255,255,0.06);
#             color: white;
#             cursor: pointer;
#             font-size: 0.95rem;
#         " onclick="navigator.clipboard.writeText('{safe}')">
#             {label}
#         </button>
#         """,
#         height=60,
#     )
# 
# 
# # Text helpers
# 
# def strip_invisible(s: str) -> str:
#     if s is None:
#         return ""
#     return (
#         s.replace("\u200b", "")
#          .replace("\u200c", "")
#          .replace("\u200d", "")
#          .replace("\ufeff", "")
#          .replace("\u00ad", "")
#     )
# 
# def normalize_spaces(s: str) -> str:
#     s = strip_invisible(s)
#     s = re.sub(r"[ \t]+", " ", s)
#     s = re.sub(r"\n{3,}", "\n\n", s)
#     return s.strip()
# 
# def clean_duplicate_signature(reply: str) -> str:
#     reply = reply.strip()
#     reply = re.sub(
#         r"(\nMit freundlichen Grüßen.*?E\.ON Kundenservice)\s*\1",
#         r"\1",
#         reply,
#         flags=re.DOTALL
#     )
#     if "E.ON Kundenservice" not in reply:
#         reply += "\n\nMit freundlichen Grüßen\n[Ihr Name]\nE.ON Kundenservice"
#     return reply
# 
# def short_summary(email_text: str, max_sentences: int = 2) -> str:
#     text = (email_text or "").strip()
#     drop_lines = []
#     for line in text.splitlines():
#         l = line.strip()
#         if not l:
#             continue
#         if re.match(r"^(hallo|guten tag|sehr geehrte|liebe|freundliche grüße|mit freundlichen grüßen)", l.lower()):
#             continue
#         drop_lines.append(l)
#     clean = " ".join(drop_lines)
#     sents = re.split(r"(?<=[\.\!\?])\s+", clean)
#     sents = [s.strip() for s in sents if s.strip()]
#     return " ".join(sents[:max_sentences]) if sents else clean[:220]
# 
# def clean_for_topic(email_text: str) -> str:
#     text = (email_text or "").strip()
#     kept = []
#     for line in text.splitlines():
#         l = line.strip()
#         if not l:
#             continue
#         if re.match(r"^(hallo|guten tag|sehr geehrte|liebe|freundliche grüße|mit freundlichen grüßen)", l.lower()):
#             continue
#         kept.append(l)
#     return " ".join(kept).strip() if kept else text
# 
# 
# # Spliting generated reply into components
# 
# CLOSING_START_RE = re.compile(
#     r"(?im)^\s*(mit freundlichen grüßen|freundliche grüße|viele grüße|beste grüße|"
#     r"mit besten grüßen|hochachtungsvoll|danke und viele grüße)\s*$"
# )
# GREETING_RE = re.compile(
#     r"(?im)^\s*(sehr geehrte|sehr geehrter|guten tag|hallo|liebe|lieber)\b"
# )
# 
# def split_reply_components(reply: str) -> dict:
#     reply = normalize_spaces(reply)
# 
#     lines = reply.splitlines()
#     while lines and not lines[0].strip():
#         lines.pop(0)
#     while lines and not lines[-1].strip():
#         lines.pop()
# 
#     if not lines:
#         return {"greeting": "", "main": "", "closing": ""}
# 
#     closing_idx = None
#     for i, line in enumerate(lines):
#         if CLOSING_START_RE.match(line.strip()):
#             closing_idx = i
#             break
# 
#     if closing_idx is not None:
#         closing = "\n".join(lines[closing_idx:]).strip()
#         body_lines = lines[:closing_idx]
#     else:
#         closing = ""
#         body_lines = lines
# 
#     greeting = ""
#     main_lines = body_lines[:]
# 
#     if body_lines and GREETING_RE.match(body_lines[0].strip()):
#         greeting_lines = [body_lines[0].strip()]
#         while main_lines and not main_lines[0].strip():
#             main_lines.pop(0)
#         main_lines = body_lines[1:]
#         while main_lines and not main_lines[0].strip():
#             main_lines.pop(0)
#         greeting = "\n".join(greeting_lines).strip()
#     else:
#         if len(body_lines[0].strip()) <= 60:
#             greeting = body_lines[0].strip()
#             main_lines = body_lines[1:]
#             while main_lines and not main_lines[0].strip():
#                 main_lines.pop(0)
# 
#     main = "\n".join(main_lines).strip()
# 
#     if not closing:
#         closing = "Mit freundlichen Grüßen\n[Ihr Name]\nE.ON Kundenservice"
# 
#     return {"greeting": greeting, "main": main, "closing": closing}
# 
# # No checkboxes: always compile all non-empty parts
# def compile_components(parts: dict) -> str:
#     chunks = []
#     for key in ("greeting", "main", "closing"):
#         val = parts.get(key, "").strip()
#         if val:
#             chunks.append(val)
#     return "\n\n".join(chunks).strip()
# 
# 
# # Loading Topic Model
# 
# @st.cache_resource
# def load_topic_tools():
#     topic_model = None
#     final_topic_names = {}
# 
#     if TOPIC_MODEL_DIR and os.path.exists(TOPIC_MODEL_DIR):
#         from bertopic import BERTopic
#         topic_model = BERTopic.load(TOPIC_MODEL_DIR)
# 
#     if TOPIC_NAMES_PATH and os.path.exists(TOPIC_NAMES_PATH):
#         with open(TOPIC_NAMES_PATH, "r", encoding="utf-8") as f:
#             for line in f:
#                 line = line.strip()
#                 if not line:
#                     continue
#                 tid, name = line.split("\t", 1)
#                 final_topic_names[int(tid)] = name
# 
#     return topic_model, final_topic_names
# 
# def get_topic_label(email_text: str, topic_model, final_topic_names) -> tuple[str, float | None, int | None]:
#     if topic_model is None:
#         return "Sonstiges", None, None
# 
#     clean_text = clean_for_topic(email_text)
#     t_ids, probs = topic_model.transform([clean_text])
#     t_id = int(t_ids[0])
# 
#     conf = None
#     if probs is not None and len(probs) > 0:
#         try:
#             conf = float(probs[0].max())
#         except Exception:
#             conf = None
# 
#     if conf is not None and conf < TOPIC_MIN_PROB:
#         return "Sonstiges", conf, t_id
# 
#     label = final_topic_names.get(t_id, f"Topic {t_id}")
#     return label, conf, t_id
# 
# 
# # Loading saved merged Model
# 
# @st.cache_resource
# def load_model():
#     if not os.path.exists(MERGED_MODEL_DIR):
#         raise RuntimeError(f"MERGED_MODEL_DIR not found: {MERGED_MODEL_DIR}")
# 
#     tokenizer = AutoTokenizer.from_pretrained(MERGED_MODEL_DIR, use_fast=False)
#     if tokenizer.pad_token is None:
#         tokenizer.pad_token = tokenizer.eos_token
# 
#     model = AutoModelForCausalLM.from_pretrained(
#         MERGED_MODEL_DIR,
#         torch_dtype=torch.float16,
#         device_map="auto",
#     )
#     model.eval()
# 
#     model.config.pad_token_id = tokenizer.pad_token_id
#     model.config.eos_token_id = tokenizer.eos_token_id
# 
#     return model, tokenizer
# 
# 
# # Generation
# 
# def build_instruction(tone: str) -> str:
#     tone = (tone or "").lower().strip()
#     if tone == "formal":
#         return (
#             "Du bist ein KI-Assistent, der Mitarbeitende im E.ON-Kundenservice unterstützt. "
#             "Formuliere eine formelle, klare und höfliche Antwort-E-Mail auf Deutsch.\n"
#             "Stilregeln:\n"
#             "- Sehr formell und sachlich\n"
#             "- Höfliche Distanz (Sie-Form)\n"
#             "- Klassische Grußformel\n"
#         )
#     return (
#         "Du bist ein KI-Assistent, der Mitarbeitende im E.ON-Kundenservice unterstützt. "
#         "Formuliere eine freundliche, empathische aber professionelle Antwort-E-Mail auf Deutsch.\n"
#         "Stilregeln:\n"
#         "- Freundlich, empathisch, aber professionell\n"
#         "- Einfachere Sprache\n"
#         "- Kürzere Sätze\n"
#     )
# 
# @torch.no_grad()
# def generate_reply(model, tokenizer, email_text: str, tone: str = "formal") -> str:
#     instr = build_instruction(tone)
# 
#     safety = (
#         "WICHTIG:\n"
#         "1) Antworte ausschließlich auf Basis der Kunden-E-Mail.\n"
#         "2) Erfinde KEINE neuen Fakten: keine Nummern, Beträge, Zählerstände, Daten/Zeiträume, Orte/Adressen, Telefon/E-Mail.\n"
#         "3) Wenn Informationen fehlen, stelle 2–4 konkrete Rückfragen.\n"
#         "4) Wenn der Kunde noch nicht gezahlt hat oder erst zahlen wird, darf nicht behauptet werden, dass bereits gezahlt/überwiesen wurde.\n"
#     )
# 
#     prompt = (
#         f"{instr}\n\n"
#         f"{safety}\n"
#         f"Kunden-E-Mail:\n{email_text}\n\n"
#         f"Antwort:\n"
#     )
# 
#     device = next(model.parameters()).device
#     inputs = tokenizer(prompt, return_tensors="pt", truncation=True, max_length=1024)
#     inputs = {k: v.to(device) for k, v in inputs.items()}
# 
#     out = model.generate(
#         **inputs,
#         do_sample=False,
#         num_beams=3,
#         repetition_penalty=1.15,
#         no_repeat_ngram_size=4,
#         max_new_tokens=MAX_NEW_TOKENS,
#         eos_token_id=tokenizer.eos_token_id,
#         pad_token_id=tokenizer.pad_token_id,
#     )
# 
#     text = tokenizer.decode(out[0], skip_special_tokens=True)
#     text = strip_invisible(text)
# 
#     reply = text.split("Antwort:", 1)[1].strip() if "Antwort:" in text else text.strip()
#     reply = normalize_spaces(reply)
#     reply = clean_duplicate_signature(reply)
#     return reply
# 
# 
# # Streamlit UI
# 
# st.set_page_config(page_title="E.ON Customer Email Assistant", layout="wide")
# st.title("E.ON Customer Email Assistant")
# 
# model, tokenizer = load_model()
# topic_model, final_topic_names = load_topic_tools()
# 
# with st.sidebar:
#     st.header("Model")
#     st.caption(f"Merged model: {MERGED_MODEL_DIR}")
# 
# email_text = st.text_area(
#     "Paste customer email here:",
#     height=220,
#     placeholder="Paste the customer email..."
# )
# 
# col1, col2 = st.columns(2)
# with col1:
#     run_formal = st.button("Generate Formal", use_container_width=True)
# with col2:
#     run_friendly = st.button("Generate Friendly", use_container_width=True)
# 
# # Session state storage for component editing
# if "formal_parts" not in st.session_state:
#     st.session_state.formal_parts = None
# if "friendly_parts" not in st.session_state:
#     st.session_state.friendly_parts = None
# if "active_mode" not in st.session_state:
#     st.session_state.active_mode = None  # "formal" or "friendly"
# 
# if email_text.strip():
#     topic, topic_conf, _ = get_topic_label(email_text, topic_model, final_topic_names)
#     summ = short_summary(email_text)
# 
#     st.subheader("Topic & Summary")
#     st.write(f"**Topic:** {topic}")
#     if topic_conf is not None:
#         st.caption(f"Topic confidence: {topic_conf:.2f} (threshold: {TOPIC_MIN_PROB:.2f})")
#     st.write(f"**Summary:** {summ}")
# 
#     # last-clicked-only behavior
#     if run_formal:
#         formal = generate_reply(model, tokenizer, email_text, "formal")
#         st.session_state.formal_parts = split_reply_components(formal)
#         st.session_state.friendly_parts = None
#         st.session_state.active_mode = "formal"
# 
#     if run_friendly:
#         friendly = generate_reply(model, tokenizer, email_text, "friendly")
#         st.session_state.friendly_parts = split_reply_components(friendly)
#         st.session_state.formal_parts = None
#         st.session_state.active_mode = "friendly"
# 
#     # Rendering only the active mode
#     if st.session_state.active_mode == "formal" and st.session_state.formal_parts is not None:
#         st.markdown("---")
#         st.subheader("Formal: Components")
# 
#         parts = st.session_state.formal_parts
#         g = st.text_area("Greeting (Formal)", value=parts["greeting"], height=80, key="g_formal")
#         m = st.text_area("Main body (Formal)", value=parts["main"], height=220, key="m_formal")
#         c = st.text_area("Closing & Signature (Formal)", value=parts["closing"], height=120, key="c_formal")
# 
#         st.session_state.formal_parts = {"greeting": g, "main": m, "closing": c}
# 
#         compiled = compile_components(st.session_state.formal_parts)
#         st.markdown("**Compiled Formal Email**")
#         st.code(compiled, language="text")
#         copy_button(compiled, "Copy compiled formal email")
# 
#     elif st.session_state.active_mode == "friendly" and st.session_state.friendly_parts is not None:
#         st.markdown("---")
#         st.subheader("Friendly: Components")
# 
#         parts = st.session_state.friendly_parts
#         g = st.text_area("Greeting (Friendly)", value=parts["greeting"], height=80, key="g_friendly")
#         m = st.text_area("Main body (Friendly)", value=parts["main"], height=220, key="m_friendly")
#         c = st.text_area("Closing & Signature (Friendly)", value=parts["closing"], height=120, key="c_friendly")
# 
#         st.session_state.friendly_parts = {"greeting": g, "main": m, "closing": c}
# 
#         compiled = compile_components(st.session_state.friendly_parts)
#         st.markdown("**Compiled Friendly Email**")
#         st.code(compiled, language="text")
#         copy_button(compiled, "Copy compiled friendly email")
# 
#     else:
#         st.info("Click 'Generate Formal' or 'Generate Friendly' to see components.")
# 
# else:
#     st.info("Paste a customer email above to begin.")
#

from google.colab import output
output.serve_kernel_port_as_window(8501)

!pkill -f streamlit || true

!nohup streamlit run app.py --server.port 8501 --server.address 0.0.0.0 \
  --server.enableCORS false --server.enableXsrfProtection false \
  > streamlit.log 2>&1 &

from google.colab import output
output.serve_kernel_port_as_iframe(8501, height=800)